#! /usr/bin/env python
#For installing the binary into multiple nodes using multiple threads.
#This file must be modified to suit the particular needs of the user. 

import threading
import os

commonchannel = 15

class MyThread ( threading.Thread ):

    def __init__ ( self, port, nodeid, channel, networkname, nodename ):
        self.port = port
        self.nodeid = nodeid
        self.channel = channel
        self.networkname = networkname
        self.nodename = nodename
        threading.Thread.__init__ ( self )

    def run ( self ):

        cmdtemp = 'java -classpath . tools.installer.installer ' + self.port +' '+ 'MIB520'+ ' '+ self.nodeid + ' '+ self.channel+ ' LiteOS.hex ' + self.networkname+ ' '+ self.nodename
        print 'For node '+self.nodeid+ ' the string is '+ cmdtemp
        fout = os.popen(cmdtemp)
        resultoutput = fout.read()
        print resultoutput
        
#total 6 threads
for i in range(1, 7):
    MyThread('COM' + str(i * 2 + 3), str(i), str(commonchannel), 'testbed', 'node'+str(i) ).start()