#! /usr/bin/env python
import threading
import os
from  subprocess import Popen, PIPE


#20 and 29 removed

commtable = [6]


class MyThread ( threading.Thread ):

    def __init__ ( self, port):
        self.port = port
        threading.Thread.__init__ ( self )

    def run ( self ):
        print 'this is comm' + self.port
        cmdtemp ='java tools.tools.ListenRawTranslator ' + self.port
        #p = Popen(['java', 'tools.tools.ListenRawTranslator', self.port],stdout= PIPE)
        fout = os.popen(cmdtemp)
        while True:
            line = fout.readline()
            if not line: break
            print line,

        
#total 9 threads
for i in range(1,2):
    commport = 'COM'+str(commtable[i-1]+1)
    MyThread(commport).start()